AllCops:
  GraphQL:
    Patterns:
      - "(?:^|/)graphql/"

GraphQL/ResolverMethodLength:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks resolver methods are not too long'
  Max: 10
  CountComments: false
  ExcludedMethods: []

GraphQL/FieldDefinitions:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks consistency of field definitions'
  EnforcedStyle: group_definitions
  SupportedStyles:
    - group_definitions
    - define_resolver_after_definition

GraphQL/FieldDescription:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Ensures all fields have a description'

GraphQL/FieldMethod:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks :method option is used for appropriate fields'

GraphQL/ExtractType:
  Enabled: true
  VersionAdded: '0.80'
  Description: 'Checks fields on common prefix groups'
  MaxFields: 2
  Prefixes:
    - is
    - with
    - avg
    - min
    - max
